#!/bin/bash
## command: xsync /opt/module/hadoop
## function: All files in the specified path are copied in a loop.

# get args count, if count == 0, then exit.
pcount=$#
if ((pcount == 0)); then
  echo "no args, please check command!!!"
  exit
fi

# get basename
p1=$1
fname=$(basename $p1)
echo fname=$fname

# get absolute path
pdir=$(
  cd -P $(dirname $p1)
  pwd
)
echo pdir=$pdir

# get current user
user=$(whoami)

# rsync file to other machine: hadoop03, hadoop04
for ((host = 3; host < 5; host++)); do
  echo ------------------- hadoop0$host --------------
  rsync -rvl $pdir/$fname $user@hadoop0$host:$pdir
done
